# -*- coding: utf-8 -*-
"""BMI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jorXz6RnKFARvPIC006lpnVAKtmIu6Cq
"""

import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files

uploaded = files.upload()

data = pd.read_csv('diabetes.csv')

data.head()

data.tail()

bmi_bins = [1,18.5,25,30,35,40,100]
bmi_labels = ["Underweight","Normal","Overweight","Obese Class 1","Obese Class 2" , "Obese 3"]
data['BMI_Category'] = pd.cut(data['BMI'], bins=bmi_bins, labels=bmi_labels)
bmi_diabetes_cases = {}
bmi_total_cases = {}

for label in bmi_labels:
  subset_df = data[data['BMI_Category'] == label]
  bmi_diabetes_cases[label] = len(data[(data['BMI_Category'] == label) & (data['Outcome'] == 1)])
  bmi_total_cases[label] = len(subset_df)

for label in bmi_labels:
  print("{}:{} diabetes cases out of {} total recorded data".format(label,bmi_diabetes_cases[label],bmi_total_cases[label]))
plt.figure(figsize=(9,5))
plt.bar(bmi_diabetes_cases.keys(),bmi_diabetes_cases.values(),color='red')
plt.title("Diabetes Cases by BMI Category")
plt.xlabel("BMI Category")
plt.ylabel("Number of Diabetes Cases")
plt.xticks(rotation=45)
plt.grid(True)
plt.show