# -*- coding: utf-8 -*-
"""HeartDiseace.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b2HeJZ9GsDN_BjiJtm2LUmE4NQkcT8KQ
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

data = pd.read_csv("heart.csv")

data.head()

data.tail()

data.info()

data.shape

data.describe()

data.columns

data.dtypes

missing_values = data.isnull().any(axis=1)
print("Rows with missing values:")
print(missing_values)

duplicate_raws = data[data.duplicated()]
print("Duplicate Rows:")
print(duplicate_raws)

data.dropna(axis=0,inplace=True)

data.drop_duplicates(inplace=True)