# -*- coding: utf-8 -*-
"""SqureChart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lRUqa_-NdlpPV_D-iv2jt11aL3l-1Isj
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

uploaded = files.upload()

data  = pd.read_csv('heart.csv')

data.head()

label_encoder = LabelEncoder()
data['Sex'] = label_encoder.fit_transform(data['Sex'])
data['ChestPainType'] = label_encoder.fit_transform(data['ChestPainType'])
data['RestingECG'] = label_encoder.fit_transform(data['RestingECG'])
data['ExerciseAngina'] = label_encoder.fit_transform(data['ExerciseAngina'])
data['ST_Slope'] = label_encoder.fit_transform(data['ST_Slope'])

x = data.drop('HeartDisease', axis=1)
y = data['HeartDisease']
rf_classifier = RandomForestClassifier()
rf_classifier.fit(x, y)

feature_importances = rf_classifier.feature_importances_
feature_importances_df = pd.DataFrame({'Feature': x.columns, 'Importance': feature_importances})
feature_importances_df = feature_importances_df.sort_values(by='Importance', ascending=False)
print("Ranked list of feature by importance:")
print(feature_importances_df)

corr_matrix = x.corr()
importances_matrix = pd.DataFrame(corr_matrix)
importances_matrix['Importance'] = feature_importances
plt.figure(figsize=(12, 8))
sns.heatmap(importances_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()